version: "3.8"
services: 
  server: 
    build: 
      context: server/
    ports: 
      - 3000:3000
    depends_on:
      - db
  web:
    build:
      context: web/
    ports:   
      - 80:80
  mongo:
    image: mongo
    ports:
      - "27017:27017"
