version: "3.8"
services: 
  server: 
    build: 
      context: server/
    image: learningplatform001.azurecr.io/server
    ports: 
      - 3000:3000
    depends_on:
      - mongo
  web:
    build:
      context: web/
    image: learningplatform001.azurecr.io/web
    ports:   
      - 80:80
  mongo:
    image: mongo
    ports:
      - "27017:27017"
#     volumes:
#       - data:/data/db
# volumes:
#   data: